#pragma once

#define FIREFLY_GAMEPAD_BUTTON_COUNT            15

#define FIREFLY_GAMEPAD_BUTTON_A                0
#define FIREFLY_GAMEPAD_BUTTON_B                1
#define FIREFLY_GAMEPAD_BUTTON_X                2
#define FIREFLY_GAMEPAD_BUTTON_Y                3
#define FIREFLY_GAMEPAD_BUTTON_LEFT_BUMPER      4
#define FIREFLY_GAMEPAD_BUTTON_RIGHT_BUMPER     5
#define FIREFLY_GAMEPAD_BUTTON_BACK             6
#define FIREFLY_GAMEPAD_BUTTON_START            7
#define FIREFLY_GAMEPAD_BUTTON_GUIDE            8
#define FIREFLY_GAMEPAD_BUTTON_LEFT_THUMB       9
#define FIREFLY_GAMEPAD_BUTTON_RIGHT_THUMB      10
#define FIREFLY_GAMEPAD_BUTTON_DPAD_UP          11
#define FIREFLY_GAMEPAD_BUTTON_DPAD_RIGHT       12
#define FIREFLY_GAMEPAD_BUTTON_DPAD_DOWN        13
#define FIREFLY_GAMEPAD_BUTTON_DPAD_LEFT        14
#define FIREFLY_GAMEPAD_BUTTON_CROSS            FIREFLY_GAMEPAD_BUTTON_A
#define FIREFLY_GAMEPAD_BUTTON_CIRCLE           FIREFLY_GAMEPAD_BUTTON_B
#define FIREFLY_GAMEPAD_BUTTON_SQUARE           FIREFLY_GAMEPAD_BUTTON_X
#define FIREFLY_GAMEPAD_BUTTON_TRIANGLE         FIREFLY_GAMEPAD_BUTTON_Y