#pragma once

#define FIREFLY_MOUSE_BUTTON_1         0
#define FIREFLY_MOUSE_BUTTON_2         1
#define FIREFLY_MOUSE_BUTTON_3         2
#define FIREFLY_MOUSE_BUTTON_4         3
#define FIREFLY_MOUSE_BUTTON_5         4
#define FIREFLY_MOUSE_BUTTON_6         5
#define FIREFLY_MOUSE_BUTTON_7         6
#define FIREFLY_MOUSE_BUTTON_8         7
#define FIREFLY_MOUSE_BUTTON_LEFT      FIREFLY_MOUSE_BUTTON_1
#define FIREFLY_MOUSE_BUTTON_RIGHT     FIREFLY_MOUSE_BUTTON_2
#define FIREFLY_MOUSE_BUTTON_MIDDLE    FIREFLY_MOUSE_BUTTON_3